export const TERRITORIES = [
  { id: "france", name: "France", flag: "FR", code: "FR",
    fonds: ["FEDER France 2021–2027", "FSE+ Emploi & Formation", "BPI France", "Plan de Relance", "Banque des Territoires"] },
  { id: "espagne", name: "Espagne", flag: "ES", code: "ES",
    fonds: ["FEDER España 2021–2027", "FSE+ España", "CDTI Innovation", "ICO Emprendedores", "Plan de Recuperación"] },
  { id: "italie", name: "Italie", flag: "IT", code: "IT",
    fonds: ["FEDER Italia 2021–2027", "FSE+ Italia", "Invitalia PMI", "SIMEST Export", "Piano Nazionale Ripresa"] },
  { id: "allemagne", name: "Allemagne", flag: "DE", code: "DE",
    fonds: ["EFRE Deutschland 2021–2027", "ESF+ Deutschland", "KfW Förderbank", "BAFA Energieeffizienz", "Gründungszuschuss"] },
  { id: "portugal", name: "Portugal", flag: "PT", code: "PT",
    fonds: ["FEDER Portugal 2030", "FSE+ Portugal", "IAPMEI PME", "Portugal Ventures", "PRR Récupération"] },
  { id: "pays-bas", name: "Pays-Bas", flag: "NL", code: "NL",
    fonds: ["EFRO Nederland 2021–2027", "ESF+ Nederland", "RVO Subsidies", "Topsectorenbeleid", "Interreg NWE"] },
  { id: "belgique", name: "Belgique", flag: "BE", code: "BE",
    fonds: ["FEDER Wallonie 2021–2027", "FSE+ Belgique", "Sowalfin Garantie", "Innoviris Bruxelles", "VLAIO Flandre"] },
  { id: "pologne", name: "Pologne", flag: "PL", code: "PL",
    fonds: ["FEDER Polska 2021–2027", "EFS+ Polska", "Polski Fundusz Rozwoju", "BGK Infrastruktura", "KPO Récupération"] },
  { id: "roumanie", name: "Roumanie", flag: "RO", code: "RO",
    fonds: ["FEDR Romania 2021–2027", "FSE+ Romania", "IMM Invest Romania", "Start-Up Nation", "PNRR Récupération"] },
  { id: "grece", name: "Grèce", flag: "GR", code: "GR",
    fonds: ["FEDER Grèce 2021–2027", "FSE+ Grèce", "ESPA 2021–2027", "TEPIX II Fonds", "TAA Résilience"] },
  { id: "hongrie", name: "Hongrie", flag: "HU", code: "HU",
    fonds: ["FEDER Hongrie 2021–2027", "FSE+ Hongrie", "Széchenyi Tőkealap", "GINOP Compétitivité", "NHP Hajrá"] },
  { id: "suede", name: "Suède", flag: "SE", code: "SE",
    fonds: ["FEDER Sverige 2021–2027", "ESF+ Sverige", "Tillväxtverket", "Almi Entreprise", "Vinnova Innovation"] },
  { id: "danemark", name: "Danemark", flag: "DK", code: "DK",
    fonds: ["FEDER Danmark 2021–2027", "ESF+ Danmark", "Erhvervsstyrelsen", "EKF Export Kredit", "GreenFund Énergie"] },
  { id: "autriche", name: "Autriche", flag: "AT", code: "AT",
    fonds: ["FEDER Österreich 2021–2027", "ESF+ Österreich", "AWS Gründerfonds", "FFG Innovation", "WKO Export"] },
  { id: "finlande", name: "Finlande", flag: "FI", code: "FI",
    fonds: ["FEDER Suomi 2021–2027", "ESF+ Suomi", "Business Finland", "Finnvera Garanties", "ELY-Centres"] },
  { id: "irlande", name: "Irlande", flag: "IE", code: "IE",
    fonds: ["FEDER Ireland 2021–2027", "ESF+ Ireland", "Enterprise Ireland", "SBCI Finance", "LEO Local Enterprise"] },
  { id: "slovaquie", name: "Slovaquie", flag: "SK", code: "SK",
    fonds: ["FEDER Slovensko 2021–2027", "ESF+ Slovensko", "SIEA Énergie", "SARIO Investissement", "SBA PME"] },
  { id: "croatie", name: "Croatie", flag: "HR", code: "HR",
    fonds: ["FEDER Hrvatska 2021–2027", "ESF+ Hrvatska", "HAMAG-BICRO", "HBOR Banque", "HZZ Emploi"] },
  { id: "lituanie", name: "Lituanie", flag: "LT", code: "LT",
    fonds: ["FEDER Lietuva 2021–2027", "ESF+ Lietuva", "INVEGA Garanties", "MITA Innovation", "LDA Développement"] },
  { id: "bulgarie", name: "Bulgarie", flag: "BG", code: "BG",
    fonds: ["FEDER България 2021–2027", "ESF+ България", "ББР Banque Dev.", "Fond des Fonds", "NKIZ Export"] },
  { id: "lettonie", name: "Lettonie", flag: "LV", code: "LV",
    fonds: ["FEDER Latvija 2021–2027", "ESF+ Latvija", "ALTUM Garanties", "LIAA Innovation", "CFLA Investissement"] },
  { id: "slovenie", name: "Slovénie", flag: "SI", code: "SI",
    fonds: ["FEDER Slovenija 2021–2027", "ESF+ Slovenija", "Spirit Slovenia", "SID Banka", "SPIRIT Export"] },
  { id: "luxembourg", name: "Luxembourg", flag: "LU", code: "LU",
    fonds: ["FEDER Luxembourg 2021–2027", "FSE+ Luxembourg", "Luxinnovation", "SNCI Finance", "Fit 4 Innovation"] },
  { id: "estonie", name: "Estonie", flag: "EE", code: "EE",
    fonds: ["FEDER Eesti 2021–2027", "ESF+ Eesti", "EAS Entreprise", "KredEx Garanties", "Startup Estonia"] },
  { id: "chypre", name: "Chypre", flag: "CY", code: "CY",
    fonds: ["FEDER Κύπρος 2021–2027", "ESF+ Κύπρος", "RIEF Innovation", "CIPA Investissement", "Recovery Plan CY"] },
  { id: "malte", name: "Malte", flag: "MT", code: "MT",
    fonds: ["FEDER Malta 2021–2027", "ESF+ Malta", "Malta Enterprise", "FinanceMalta", "MFIN Développement"] },
  { id: "republique-tcheque", name: "République tchèque", flag: "CZ", code: "CZ",
    fonds: ["FEDER Česko 2021–2027", "ESF+ Česko", "CzechInvest", "ČMZRB Garantie", "MPO Innovation"] },
  { id: "nouvelle-caledonie", name: "Nouvelle-Calédonie", flag: "NC", code: "NC",
    fonds: ["FIDES", "ACE Entrepreneuriat", "Subvention Agricole", "DEFI Jeunes", "Formation Pro"] },
  { id: "martinique", name: "Martinique", flag: "MQ", code: "MQ",
    fonds: ["FEDER 2021–2027", "FSE+ Emploi & Formation", "LEADER Agriculture & Rural", "BPI France Outre-Mer", "Subvention CTM"] },
  { id: "polynesie-francaise", name: "Polynésie française", flag: "PF", code: "PF",
    fonds: ["SEFI", "FDA Archipels", "Tourisme Durable", "ALS Logement", "FSP Solidarité"] },
  { id: "guadeloupe", name: "Guadeloupe", flag: "GP", code: "GP",
    fonds: ["FEDER Guadeloupe", "FSE+", "Plan de Relance", "Subvention Région", "ADIE Microfinancement"] },
  { id: "reunion", name: "La Réunion", flag: "RE", code: "RE",
    fonds: ["FEDER Réunion", "Aide Région Réunion", "FSE+", "NACRE", "DEETS Cohésion"] },
];

export const SECTEUR_KEYS = [
  "secteur_creation", "secteur_innovation", "secteur_agriculture",
  "secteur_environnement", "secteur_tourisme", "secteur_logement",
  "secteur_formation", "secteur_culture", "secteur_sante", "secteur_autre",
];

export const SECTEUR_FR_VALUES = [
  "Création d'entreprise", "Innovation & Numérique", "Agriculture & Pêche",
  "Environnement & Énergie", "Tourisme", "Logement social",
  "Formation & Emploi", "Culture & Sport", "Santé & Social", "Autre",
];
