const colors = {
  light: {
    text: "#0D1F3C",
    tint: "#B5872A",
    background: "#F1F4FA",
    foreground: "#0D1F3C",
    card: "#FFFFFF",
    cardForeground: "#0D1F3C",
    primary: "#0D1F3C",
    primaryForeground: "#FFFFFF",
    secondary: "#F1F4FA",
    secondaryForeground: "#4B5574",
    muted: "#EEF0F7",
    mutedForeground: "#6B7896",
    accent: "#B5872A",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#DDE2EC",
    input: "#DDE2EC",
    gold: "#B5872A",
    goldLight: "#D4A847",
    navy: "#0D1F3C",
    navyLight: "#1A3561",
    success: "#16A34A",
    successBg: "#F0FDF4",
    warning: "#D97706",
    warningBg: "#FFFBEB",
    info: "#2563EB",
    infoBg: "#EFF6FF",
  },
  radius: 14,
};

export default colors;
