// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/financement/LandingPage.tsx": () => import("../components/mockups/financement/LandingPage.tsx"),
  "./components/mockups/financement/pages/AdminDashboard.tsx": () => import("../components/mockups/financement/pages/AdminDashboard.tsx"),
  "./components/mockups/financement/pages/AdminDossiers.tsx": () => import("../components/mockups/financement/pages/AdminDossiers.tsx"),
  "./components/mockups/financement/pages/AdminFrais.tsx": () => import("../components/mockups/financement/pages/AdminFrais.tsx"),
  "./components/mockups/financement/pages/Landing.tsx": () => import("../components/mockups/financement/pages/Landing.tsx"),
  "./components/mockups/financement/pages/Login.tsx": () => import("../components/mockups/financement/pages/Login.tsx"),
  "./components/mockups/financement/pages/Register.tsx": () => import("../components/mockups/financement/pages/Register.tsx"),
  "./components/mockups/financement/pages/UserDashboard.tsx": () => import("../components/mockups/financement/pages/UserDashboard.tsx"),
  "./components/mockups/financement/pages/UserDocuments.tsx": () => import("../components/mockups/financement/pages/UserDocuments.tsx"),
  "./components/mockups/financement/pages/UserDossier.tsx": () => import("../components/mockups/financement/pages/UserDossier.tsx"),
  "./components/mockups/financement/pages/UserPaiement.tsx": () => import("../components/mockups/financement/pages/UserPaiement.tsx"),
  "./components/mockups/financement/pages/UserSuivi.tsx": () => import("../components/mockups/financement/pages/UserSuivi.tsx"),
  "./components/mockups/financement/shared/AdminLayout.tsx": () => import("../components/mockups/financement/shared/AdminLayout.tsx"),
  "./components/mockups/financement/shared/UserLayout.tsx": () => import("../components/mockups/financement/shared/UserLayout.tsx")
};
